### ISSUE TITLE
4:04 AM MTAStack failed: Error: The stack named MTAStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE

### ISSUE THREAD

**Issue by optimisticwaqar** [aws-samples/medical-transcription-analysis#85]
@alexchirayath  Even after updating the nodejs to the latest version still getting the following issue/error, Please help

MTAStack failed: Error: The stack named MTAStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/home/fawad/medical-transcription-analysis/app/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/home/fawad/medical-transcription-analysis/app/node_modules/aws-cdk/lib/api/deploy-stack.ts:337:26)
    at CdkToolkit.deploy (/home/fawad/medical-transcription-analysis/app/node_modules/aws-cdk/lib/cdk-toolkit.ts:194:24)
    at initCommandLine (/home/fawad/medical-transcription-analysis/app/node_modules/aws-cdk/bin/cdk.ts:267:9)
The stack named MTAStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
Error: The stack named MTAStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/home/fawad/medical-transcription-analysis/app/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/home/fawad/medical-transcription-analysis/app/node_modules/aws-cdk/lib/api/deploy-stack.ts:337:26)
    at CdkToolkit.deploy (/home/fawad/medical-transcription-analysis/app/node_modules/aws-cdk/lib/cdk-toolkit.ts:194:24)
    at initCommandLine (/home/fawad/medical-transcription-analysis/app/node_modules/aws-cdk/bin/cdk.ts:267:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

![image](https://user-images.githubusercontent.com/65467250/141593719-a505c2a5-91f0-4f52-aaf7-35b4161cf70a.png)

**Comment by optimisticwaqar** [comment]
I am trying this solution on my local computer with Ubuntu 20.04 . But it is giving the MTAStack issue which i already mentioned and asked about on disqus.com blog. Can you help me  how to resolve this issue? Please note that i updated the CDK and nodejs to latest version like 14.x and 16.x but the problem still exist. Is it an issue of trying this solution on local system? Shall i try it on an EC2 instance, is that necessary? @alexchirayath

**Comment by alexchirayath** [comment]
Hey @optimisticwaqar 
Thanks for reaching out.
The logs show that the issue is because the table name already exists. 

The fix for you is to 
- Delete the DynamoDB tables in the region and account you are trying to deploy - Patients, HealthCareProfessionals and Sessions tables
- Redeploy the stack 


The reason  is because you may have created a deployment already and when the  stack was deleted, some resources were retained. The MTA stack originally used to retain data sources (as a way to protect accidental data deletion) and hence S3 buckets and DynamoDB tables were left without being deleted. However, the recent PR https://github.com/aws-samples/medical-transcription-analysis/pull/84/ now addresses these and by default deletes all resources created as part of the MTA deployments. Let me know if that works

**Comment by optimisticwaqar** [comment]
Hi @alexchirayath, thanks for the quick response and guidance. I will try the proposed fix and will let you know if it work or not.

**Comment by optimisticwaqar** [comment]
Hey @alexchirayath , finally it works :-) thanks for the help and guidance.
